### ISSUE TITLE
Ethics

### ISSUE THREAD

**Issue by lyda** [katahiromz/XScreenSaverWin#13]
I know you've put a fair bit of work into this, but the original author asked folks [not to port this to Windows]
(https://www.jwz.org/xscreensaver/xscreensaver-windows.html). Yes, you can do so legally, but there are lots of things we legally can do but don't because of ethics or etiquette.

We don't really want a world where there has to be a law for everything, do we? Surely having ethics and basic manners to guide our behaviour more than laws and rules would be a better path?

**Comment by katahiromz** [comment]
Hehehe, if you're born without ethics, should you die?
If living in your country was illegal, then do you want to be a dead man? 

I'm an existence beyond the ethics. I will make the world a different place in the meanings of living.

**Comment by katahiromz** [comment]
--- "I hate the earth man. The earth man is killing people on the earth. The earth man commit crimes. You should not use the earth man's computer."

**Comment by katahiromz** [comment]
The personal feelings are not ethics.

**Comment by katahiromz** [comment]
Believe. Maybe there're good persons even in Microsoft.

**Comment by katahiromz** [comment]
Is Jesus Christ white in your star? It's OK, although it hurts our star feelings. Our star admits the fact that the earth is an independent civilization.

**Comment by katahiromz** [comment]
Please show the proof that every Microsoft person is evil or criminal.
If you cannot prove it, then you cannot stop me.

**Comment by katahiromz** [comment]
"If you hate a priest, and you will hate his very vestments."

**Comment by katahiromz** [comment]
If he just hates Microsoft and he can't understand the reason that Microsoft had won in the world market, then he is a true fool.

**Comment by katahiromz** [comment]
I'm a pro-Microsoft and anti-Microsoft. It's both.

**Comment by a13** [comment]
I can reproduce this one

**Comment by a13** [comment]
Ethics …
