### ISSUE TITLE
Compiler errors in VS

### ISSUE THREAD

**Issue by ParzivalWolfram** [katahiromz/XScreenSaverWin#16]
I opened the generated project files and tried to compile. [Build log here.](https://github.com/katahiromz/XScreenSaverWin/files/2448517/build.log)

224 build operations failed.

**Comment by katahiromz** [comment]
What version of Visual Studio did you use?

**Comment by ParzivalWolfram** [comment]
Version reported by CMake as "Visual Studio 15 2017". Installed version is
Visual Studio Express 2017, x64 architecture.
Running on Windows 10, x64 architecture. 16GB RAM, 3.3GHz quad-core AMD CPU.

**Comment by katahiromz** [comment]
This program is oldie toy. Visual Studio 2017 is not supported yet. If we support VS2017, then it requires many changes. Sorry.
