### ISSUE TITLE
Respecting Jamie Zawinski's wishes

### ISSUE THREAD

**Issue by Amaroq-Clearwater** [katahiromz/XScreenSaverWin#19]
While I admire a lot of the work you're doing, and also appreciate a good screensaver, I feel like it is important to bring this up.

The original creator of XScreenSaver specifically requested that nobody make ports of his program to Windows.

You even linked to his website in the ReadMe, which makes wonder why you're not respecting his wishes.

https://www.jwz.org/xscreensaver/xscreensaver-windows.html

I'm really sorry for bringing this up. It just feels wrong of me not to.

If you'd prefer to discuss this issue in private and close this ticket, then I will happily provide you with my contact information.

**Comment by katahiromz** [comment]
I do not compromise on such disgusting hate crimes or computing limitations. If the authors want to succeed in his business, then they should be fair to any users. Windows users are not evil.

**Comment by Amaroq-Clearwater** [comment]
Believe it or not, I actually share your view here. I look forward to
seeing future development on this port :3

Who knows, after this long, chances are he's finally gotten it out of his
system.

**Comment by Rav4s** [comment]
Jamie Zawinski has respectfully asked for XScreenSaver to not be ported to Windows. He even gave his entire backstory about how he personally (and his company) has been mistreated by Microsoft.

From his website: "Sometimes they just don't care about ethics or the wishes of a creator. Some people have the sociopathic attitude that if it is legal to do something, then that also makes it right."

@katahiromz It is very disrespectful to continue developing this port, and it shows complete disregard for the 25+ years of Jamie Zawinski's work.

**Comment by smmckay** [comment]
Notice how jwz has cleverly conflated not doing what jwz wants with having no morals. It's entirely possible to have a principled position in opposition to him, and even likely in this situation, seeing as how his position is that doing something he doesn't like is evil.

**Comment by katahiromz** [comment]
Please buy Microsoft stock and enjoy! Happiness is there.

**Comment by BenLeggiero** [comment]
If y'all want to feel better about this project, sent JWZ some money. He deserves to be rewarded for his work.

I also think he has... an unreasonable expectation for users' ability to switch operating systems. For folks who just want a neat screensaver but don't have the luxury of leaving Windows, I think this project overall improves the happiness in the world, without tilting the needle towards Microsoft in any significant way.

@Amaroq-Clearwater @Rav4s @smmckay et al

**Comment by the-architect-2030** [comment]
I believe anyone should be free to do whatever they want with their own free open source software copy. If anyone wants to modify and redistribute XScreenSaver in any way, they should be free to do so.

Personally, i am against porting XScreenSaver to Windows not cuz Jamie Zawinski don't want that, but cuz i believe Windows and other closed source software are Malware and should be avoided.
