### ISSUE TITLE
WhirlWindWarp slower on Windows 11 than on any Linux Distro

### ISSUE THREAD

**Issue by DanyGee** [katahiromz/XScreenSaverWin#22]
I don't know why WhirlWindWarp screensaver is so slow on Windows 11 (particles fly at least 75% slower).
I'm happy that it works at all, but it needs to be as snappy on Windows as on Linux to maintain its original, pleasant dynamics.
Can anyone explain the reasons and provide a fix (if possible)?

OS: Windows 11 Pro [64-bit]                     
Kernel: 10.0.22000.0                            
Motherboard: ASUSTeK COMPUTER INC. Z170-DELUXE                                                           
Resolution: 3840x2160                                         
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz   
GPU: NVIDIA GeForce GTX 1080                    
Memory:    [ ■■-------- ] 11.64 GiB / 63.93 GiB

**Comment by katahiromz** [comment]
https://github.com/katahiromz/XScreenSaverWin/blob/master/common/xws2win.c
https://github.com/katahiromz/XScreenSaverWin/blob/master/nongl-savers/whirlwindwarp.c
Have a look at these files. 

`XFillRectangle` and `XDrawRectangle` functions are emulated from X11 to Win32. The emulation of these functions are slow as you look.

**Comment by DanyGee** [comment]
OK, thanks for the explanation.
Is any workaround/fix planned?

**Comment by katahiromz** [comment]
A little optimized now.
