### ISSUE TITLE
Doesn't run properly on a dual monitor setup

### ISSUE THREAD

**Issue by katahiromz** [katahiromz/XScreenSaverWin#4]
From: Paul White phwhite@gmail.com

> Hello,
> 
> I just wanted to thank you and let you know I was able to get it working on Windows 10, when only using one monitor.  It seems it doesn't run properly on a dual monitor setup.
> 
> Thanks for your porting efforts.
> Best Wishes,
> Paul

**Comment by wporter82** [comment]
I would like to add to this by saying that on a dual monitor system it will stretch the display area to cover both but will only render in 1/2 of each screen since it assumes the aspect ratio of just 1 monitor and not the combination of both. Not all do this, but it appears the OpenGL ones tend to do it the most.

**Comment by katahiromz** [comment]
Which are ones?

**Comment by katahiromz** [comment]
I added multimonitor support and make a version up to 0.79. Try it.

**Comment by katahiromz** [comment]
Could you test this and report to me?

https://onedrive.live.com/download?resid=394BB567F81F3639!148&authkey=!ANGZP6u0VDf6XUc&ithint=file%2czip

**Comment by wporter82** [comment]
The 3 tested ok. 2 monitor works well now too.

On Wed, Mar 9, 2016 at 7:16 PM, Katayama Hirofumi MZ <
notifications@github.com> wrote:

> Could you test this and report to me?
>
>
> https://onedrive.live.com/download?resid=394BB567F81F3639!148&authkey=!ANGZP6u0VDf6XUc&ithint=file%2czip
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/katahiromz/XScreenSaverWin/issues/4#issuecomment-194641129>
> .
>



-- 
Wayne Porter
(619) 270-6377

**Comment by katahiromz** [comment]
Thanks. Version up to 0.80.
