### ISSUE TITLE
Memory error when exit for some WGL screensaver

### ISSUE THREAD

**Issue by tumagonx** [katahiromz/XScreenSaverWin#5]
Firstly huge thanks for the win32 port! been looking for kumppa and carousel.

I'm running on Windows 8.1 64bit and XP 32bit (english), Intel HD Graphics
Some of WGL screensaver exit with memory error like:
![carousel](https://cloud.githubusercontent.com/assets/4075264/12520461/5017b86a-c177-11e5-8a33-7c32e6853a31.png)

Also tried on Virtualbox (Win7) with the same error

When I try to debug it show hack_free() in wgl.c as the trigger. I'm no sure if this crash specific to hardware or not but commenting hack_free() make the error gone for me.

Version 0.77

**Comment by katahiromz** [comment]
Thanks for reporting. I added null check of hack_free() and make a version up to 0.78.

**Comment by tumagonx** [comment]
thank you!
