### ISSUE TITLE
OSS

### ISSUE THREAD

**Issue by totano** [katahiromz/XScreenSaverWin#6]
Are you making people pay for a port of a FREE software hosted on Github?
Is that even possible?

**Comment by katahiromz** [comment]
Yes.

**Comment by katahiromz** [comment]
See license.

**Comment by smileytechguy** [comment]
Thats not cool, not at all.

**Comment by katahiromz** [comment]
Indeed. You know it, I know it.

**Comment by smileytechguy** [comment]
Then why are you making us pay for it?

**Comment by katahiromz** [comment]
God of money knows.

**Comment by smileytechguy** [comment]
How much money do you actually make?

**Comment by katahiromz** [comment]
Mind your business.

**Comment by cascent** [comment]
thank you for resolving this
